@startuml Chess

	class Chess
	class Turn
	class Player
	class Board

	class Piece
	class Pawn
	class Rook
	class Knight
	class Bishop
	class Queen
	class King

	class Color
	class White
	class Black
	class Move

	Chess *--> Turn
	Chess *--> Board
	Chess *--> "2" Player

	Turn *--> "2" Player

	Board o--> "32" Piece

	Player ..> Move
	Player *--> Color
	Player o--> Piece
	Player *-- King
	Player *-- Queen
	Player *-- "2" Bishop
	Player *-- "2" Knight
	Player *-- "2" Rook
	Player *-- "8" Pawn
	Player ..> "*" Movement

	Color <|-- White
	Color <|-- Black

	Piece --> "1" Move
	Piece <|-- Pawn
	Piece <|-- Bishop
	Piece <|-- Knight
	Piece <|-- Rook
	Piece <|-- Queen
	Piece <|-- King
	Piece o--> Position

	Move *-- Destination
	Move *-- Quantity
	Move o--> "2" Position

	Destination <|-- toFreeSquare
	Destination <|-- toOpponentSquare

	Move <|-- Horizontal
	Move <|-- Vertical
	Move <|-- Diagonal
	Move <|-- L

	Quantity <|-- One
	Quantity <|-- Many
@enduml
